### ISSUE TITLE
Why did you not continue in development of this library?

### ISSUE THREAD

**Issue by ducho** [struzik-vladislav/epp-client#2]
Hi Vladislav!
Why did you not continue in development of this library?
I wanted to try use your library but I missing StreamSocketConnection class... ;)
Thanks and regards!
Dusan.

**Comment by struzik-vladislav** [comment]
Hi @ducho !
I suspended the development due to lack of free time. You can write me an issue and send your pull requests. I will consider them.
The StreamSocketConnection class located in `struzik-vladislav/epp-socket-connection`. Please look `suggest` section in composer.json. I made a stream socket connection in a separate library to enable the substitute connection class. And also later I wanted to develop a RabbitMQ connection.

**Comment by struzik-vladislav** [comment]
Hi @ducho !
The EPPClient V2 is released. The new extension is released - [struzik-vladislav/epp-ext-secdns](https://github.com/struzik-vladislav/epp-ext-secdns). RabbitMQ connection and deamon will be released soon. You can watch all related libraries in the [README](https://github.com/struzik-vladislav/epp-client/blob/master/README.md).
Sincerely, Vladislav.
